version: '3.1'
services:
  personnel-svc:
    build: .
    environment:
      LOGLEVEL: 2 # 0 - OFF, 1 - ERROR, 2 - DEBUG
      # SERVER_IP: 127.0.0.1 # override for network-based auto-detected ip address
      SERVER_HOSTNAME: localhost
      SERVER_PORT: 8701
      EUREKA_APP: personnel-svc
      EUREKA_ID: personnel-one
      EUREKA_HOST: 172.24.0.2
      EUREKA_PORT: 8761
      PGHOST: postgres_container
      PGPASSWORD: secretpassword
      PGDATABASE: mydb
      PGUSER: dbuser
      PGDATA: /data/postgres  
      PGPORT: 5432
    ports:
      - 8701:8701
    networks:
      - nemocnice-network
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
        - pgadmin:/data/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
  nemocnice-network:
    external:
      name: nemocnice-network
volumes:
  postgres:
  pgadmin:
