version: '3.1'
services:
  server:
    build: .
    environment:
      PGHOST: postgres_container
      PGPASSWORD: secretpassword
      PGDATABASE: mydb
      PGUSER: dbuser
      PGDATA: /data/postgres  
      PGPORT: 5432
    ports:
      - 8701:8701
    networks:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
        - pgadmin:/data/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: